---
slurm_pam_lib_dir: /lib/aarch64-linux-gnu/security

slurm_build_deps:
  - build-essential
  - libmunge-dev
  - libmariadb-dev
  - libmariadbclient-dev
  - libpam0g-dev
  - python3-minimal
  - ruby-dev
  - wget

slurm_pmix_deps:
  - build-essential
  - libev-dev
  - libevent-dev

slurm_hwloc_deps:
  - build-essential
